version: '3.2'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.dev
            args:
                - HOST_UID=${HOST_UID}
                - HOST_GUID=${HOST_GUID}
        volumes:
            - .:/var/www/html
            - ${HOST_COMPOSER_HOME}:/var/www/html/var/.composer
        environment:
            - COMPOSER_HOME=/var/www/html/var/.composer
            - XDEBUG_ENABLED
            - XDEBUG_CONFIG
            - PHP_IDE_CONFIG
    db:
        image: postgres:12-alpine
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_PORT
        ports:
            - "${EXTERNAL_POSTGRES_PORT}:${POSTGRES_PORT}"
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile.dev
            args:
                - HOST_UID=${HOST_UID}
                - HOST_GUID=${HOST_GUID}
        depends_on:
            - php
        ports:
            - ${EXTERNAL_HTTP_PORT}:80
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
        environment:
            - UPSTREAM=php:9000

volumes:
    db: